algoritmo "Impar ou par"
// Função : Identificar se número é impar ou par
// Autor : Maysa Voinarski
// Data : 25/08/2023
// Seção de Declarações 
var
 Num : inteiro
 par : inteiro
 res : REAL
 imp : inteiro
inicio

      Escreval("Digite um número: ")
      leia(num)
      
      Se (num mod 2 = 0) entao
         Escreval("Esse número é par...")
      SeNao
           Escreval("Esse número é impar...")
      FIMSE
fimalgoritmo
