algoritmo "Repita ate que imprima 50 números pares"
// Função : Repita ate que imprima 50 números pares
// Autor : Maysa Voinarski
// Data : 26/08/2023
// Seção de Declarações 
var

num : inteiro
num2 : inteiro

inicio
      num <- 2
      num2 <- 1

      Repita
            Escreval(num)
            num <- num + 2
            num2 <- num2 + 1
      ate  num2 > 50

fimalgoritmo
