algoritmo "Vetor Soma"
// Função : Realizar a soma dos vetores
// Autor : Maysa Voinarski
// Data : 28/08/2023
// Seção de Declarações 
var
 numdig : vetor [1..5] de inteiro
 num : inteiro
 soma : inteiro
inicio

      Para num de 1 ate 5 faca
           Escreval("Digite um número: ")
           leia(numdig[num])
      soma <- soma + numdig [num]
      FimPara
      
      Escreval
      Escreval("A soma dos números digitados é: ", soma)
fimalgoritmo
